In [777]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from astropy import units as u
from astropy import constants as const

In [778]:
ast = pd.read_csv("/Users/sophiachoi/python_decal_fall25/course_assignments/homework9/solar_system.csv")

In [779]:
ast.shape
#20 rows, 11 columns

(20, 11)

In [780]:
df = ast.set_index("Attribute").T
#Switches rows and columns. Attribute column was set as the index, so it is not counted as a row
#Basically turned the attribute column into the names of each row

In [781]:
df.shape

(10, 20)

In [782]:
df.index.name = "Planet"
#changes the index name to planet, shape is same

In [783]:
df.shape

(10, 20)

In [784]:
df.reset_index(inplace=True)
#changes the index into a regular column, df now has a numbered index

In [785]:
df.shape

(10, 21)

In [786]:
df.columns.name = None
#clears any columns with a name, shape stays same bc none do

In [787]:
df.shape
#The attribute column was changed to become the index, which removed it. Meanwhile, when the index was reset, the 
#previous index "planet" was changed into its own column.

(10, 21)

In [788]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [789]:
#with units: mass, diameter, density, gravity, escape velocity, rotation period, length of day, distance from sun,
#perihelion, aphelion, orbital period, obliquity to orbit, mean temperature, surface pressure

#without units: planet, orbital eccentricity, number of moons, ring system?, global magnetic field?

In [790]:
print(df)

    Planet Mass (10^24kg) Diameter (km) Density (kg/m^3) Gravity (m/s^2)  \
0  Mercury          0.330          4879             5429             3.7
1    Venus           4.87         12104             5243             8.9
2    Earth           5.97         12756             5514             9.8
3     Moon          0.073          3475             3340             1.6
4     Mars          0.642          6792             3934             3.7
5  Jupiter           1898        142984             1326            23.1
6   Saturn            568        120536              687             9.0
7   Uranus           86.8         51118             1270             8.7
8  Neptune            102         49528             1638            11.0
9    Pluto         0.0130          2376             1850             0.7

  Escape Velocity (km/s) Rotation Period (hours) Length of Day (hours)  \
0                    4.3                  1407.6                4222.6
1                   10.4                 -5832.5                2802.0
2                   11.2                    23.9                  24.0
3                    2.4                   655.7                 708.7
4                    5.0                    24.6                  24.7
5                   59.5                     9.9                   9.9
6                   35.5                    10.7                  10.7
7                   21.3                   -17.2                  17.2
8                   23.5                    16.1                  16.1
9                    1.3                  -153.3                 153.3

  Distance from Sun (10^6 km) Perihelion (10^6 km)  ... Orbital Period (days)  \
0                        57.9                 46.0  ...                  88.0
1                       108.2                107.5  ...                 224.7
2                       149.6                147.1  ...                 365.2
3                       0.384                0.363  ...                  27.3
4                       228.0                206.7  ...                 687.0
5                       778.5                740.6  ...                  4331
6                      1432.0               1357.6  ...                 10747
7                      2867.0               2732.7  ...                 30589
8                      4515.0               4471.1  ...                 59800
9                      5906.4               4436.8  ...                 90560

  Orbital Velocity (km/s) Orbital Inclination (deg) Orbital Eccentricity  \
0                    47.4                       7.0                0.206
1                    35.0                       3.4                0.007
2                    29.8                       0.0                0.017
3                     1.0                       5.1                0.055
4                    24.1                       1.8                0.094
5                    13.1                       1.3                0.049
6                     9.7                       2.5                0.052
7                     6.8                       0.8                0.047
8                     5.4                       1.8                0.010
9                     4.7                      17.2                0.244

  Obliquity to Orbit (deg) Mean Temperature (C) Surface Pressure (bars)  \
0                    0.034                  167                       0
1                    177.4                  464                      92
2                     23.4                   15                       1
3                      6.7                  -20                       0
4                     25.2                  -65                    0.01
5                      3.1                 -110                 Unknown
6                     26.7                 -140                 Unknown
7                     97.8                 -195                 Unknown
8                     28.3                 -200                 Unknown
9                    119.5                 -225                 0.00001

  Number of Moons Ring System? Global Magnetic Field?
0               0           No                    Yes
1               0           No                     No
2               1           No                    Yes
3               0           No                     No
4               2           No                     No
5              95          Yes                    Yes
6             274          Yes                    Yes
7              28          Yes                    Yes
8              16          Yes                    Yes
9               5           No                Unknown

[10 rows x 21 columns]

In [791]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [792]:
for col in df.columns:
    print(df[col].apply(type))

#The values are strings, which is a problem for data analysis because trying to perform numeric functions on them 
#won't work. For example, graphing is impossible and adding two strings will only combine them together instead of
#adding the numbers they're meant to be ("1" + "2" = "12" instead of 1+2=3)

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [793]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [794]:
not_these = ["Planet", "Ring System?", "Global Magnetic Field?"]

for col in df.columns:
    if col not in not_these:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [795]:
df.dtypes
#Objects, floats, and integers
#Floats include decimals, integers are integers, and the objects don't contain numbers so they can't be switched to them

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [796]:
def attach_units(col, unit, new_col):
    new_values = []
    for val in df[col]:
        new_values.append(val * unit)    
    df[col] = new_values
    df.rename(columns={col: new_col}, inplace=True)
    return df

In [797]:
attach_units('Escape Velocity (km/s)', u.km/u.s, 'Escape Velocity (km/s)')

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3 km / s,1407.6,4222.6,57.900,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4 km / s,-5832.5,2802.0,108.200,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2 km / s,23.9,24.0,149.600,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4 km / s,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0 km / s,24.6,24.7,228.000,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5 km / s,9.9,9.9,778.500,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5 km / s,10.7,10.7,1432.000,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3 km / s,-17.2,17.2,2867.000,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5 km / s,16.1,16.1,4515.000,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3 km / s,-153.3,153.3,5906.400,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [798]:
print(df['Escape Velocity (km/s)'])

0     4.3 km / s
1    10.4 km / s
2    11.2 km / s
3     2.4 km / s
4     5.0 km / s
5    59.5 km / s
6    35.5 km / s
7    21.3 km / s
8    23.5 km / s
9     1.3 km / s
Name: Escape Velocity (km/s), dtype: object

In [799]:
attach_units('Perihelion (10^6 km)', 1e6 * u.km, 'Perihelion (km)')
attach_units('Aphelion (10^6 km)', 1e6 * u.km, 'Aphelion (km)')

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3 km / s,1407.6,4222.6,57.900,46000000.0 km,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4 km / s,-5832.5,2802.0,108.200,107500000.0 km,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2 km / s,23.9,24.0,149.600,147100000.0 km,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4 km / s,655.7,708.7,0.384,363000.0 km,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0 km / s,24.6,24.7,228.000,206700000.0 km,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5 km / s,9.9,9.9,778.500,740600000.0 km,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5 km / s,10.7,10.7,1432.000,1357600000.0 km,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3 km / s,-17.2,17.2,2867.000,2732700000.0 km,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5 km / s,16.1,16.1,4515.000,4471100000.0 km,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3 km / s,-153.3,153.3,5906.400,4436800000.0 km,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [800]:
semi_major = (df['Perihelion (km)'] + df['Aphelion (km)']) / 2
idx = df.columns.get_loc('Aphelion (km)')
df.insert(idx + 1, "Semi-Major Axis (km)", semi_major)

In [801]:
df["Semi-Major Axis (km)"]

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: Semi-Major Axis (km), dtype: object

In [802]:
attach_units('Orbital Period (days)', 1/365 * u.yr, 'Orbital Period (years)')

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (km),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3 km / s,1407.6,4222.6,57.900,46000000.0 km,...,0.2410958904109589 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4 km / s,-5832.5,2802.0,108.200,107500000.0 km,...,0.6156164383561643 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2 km / s,23.9,24.0,149.600,147100000.0 km,...,1.0005479452054795 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4 km / s,655.7,708.7,0.384,363000.0 km,...,0.0747945205479452 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0 km / s,24.6,24.7,228.000,206700000.0 km,...,1.8821917808219177 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5 km / s,9.9,9.9,778.500,740600000.0 km,...,11.865753424657534 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5 km / s,10.7,10.7,1432.000,1357600000.0 km,...,29.443835616438356 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3 km / s,-17.2,17.2,2867.000,2732700000.0 km,...,83.8054794520548 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5 km / s,16.1,16.1,4515.000,4471100000.0 km,...,163.83561643835617 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3 km / s,-153.3,153.3,5906.400,4436800000.0 km,...,248.1095890410959 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [803]:
print(df['Orbital Period (years)'])

0    0.2410958904109589 yr
1    0.6156164383561643 yr
2    1.0005479452054795 yr
3    0.0747945205479452 yr
4    1.8821917808219177 yr
5    11.865753424657534 yr
6    29.443835616438356 yr
7      83.8054794520548 yr
8    163.83561643835617 yr
9     248.1095890410959 yr
Name: Orbital Period (years), dtype: object

In [804]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (km)', 'Aphelion (km)', 'Semi-Major Axis (km)',
       'Orbital Period (years)', 'Orbital Velocity (km/s)',
       'Orbital Inclination (deg)', 'Orbital Eccentricity',
       'Obliquity to Orbit (deg)', 'Mean Temperature (C)',
       'Surface Pressure (bars)', 'Number of Moons', 'Ring System?',
       'Global Magnetic Field?'],
      dtype='object')

In [805]:
earth_period = df.loc[2, 'Orbital Period (years)']
print(f"{earth_period:.4f}")

1.0005 yr

In [806]:
#AU, or astronomical unit, is a way to measure distances within our solar system without having to use unnecessarily
#large values (like any common multiplier of meters)

In [807]:
print(const.au)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [808]:
u.au.to(u.km)

149597870.7

In [809]:
attach_units('Diameter (km)', u.km, 'Diameter (km)')

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (km),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879.0 km,5429,3.7,4.3 km / s,1407.6,4222.6,57.900,46000000.0 km,...,0.2410958904109589 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104.0 km,5243,8.9,10.4 km / s,-5832.5,2802.0,108.200,107500000.0 km,...,0.6156164383561643 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756.0 km,5514,9.8,11.2 km / s,23.9,24.0,149.600,147100000.0 km,...,1.0005479452054795 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475.0 km,3340,1.6,2.4 km / s,655.7,708.7,0.384,363000.0 km,...,0.0747945205479452 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792.0 km,3934,3.7,5.0 km / s,24.6,24.7,228.000,206700000.0 km,...,1.8821917808219177 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984.0 km,1326,23.1,59.5 km / s,9.9,9.9,778.500,740600000.0 km,...,11.865753424657534 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536.0 km,687,9.0,35.5 km / s,10.7,10.7,1432.000,1357600000.0 km,...,29.443835616438356 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118.0 km,1270,8.7,21.3 km / s,-17.2,17.2,2867.000,2732700000.0 km,...,83.8054794520548 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528.0 km,1638,11.0,23.5 km / s,16.1,16.1,4515.000,4471100000.0 km,...,163.83561643835617 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376.0 km,1850,0.7,1.3 km / s,-153.3,153.3,5906.400,4436800000.0 km,...,248.1095890410959 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [810]:
df["Diameter (km)"].map(type).unique()

array([<class 'astropy.units.quantity.Quantity'>], dtype=object)

In [811]:
def to_AU(col):
    if not isinstance(df[col].iloc[0], u.Quantity):
        df[col] = df[col].values * u.km
    df[col] = df[col].apply(lambda x: x.to(u.au))

to_AU('Diameter (km)')
df.rename(columns={'Diameter (km)': 'Diameter (AU)'}, inplace=True)

In [812]:
to_AU('Aphelion (km)')
df.rename(columns={'Aphelion (km)': 'Aphelion (AU)'}, inplace=True)

In [813]:
to_AU('Perihelion (km)')
df.rename(columns={'Perihelion (km)': 'Perihelion (AU)'}, inplace=True)

In [814]:
to_AU('Semi-Major Axis (km)')
df.rename(columns={'Semi-Major Axis (km)': 'Semi-Major Axis (AU)'}, inplace=True)

In [815]:
attach_units('Distance from Sun (10^6 km)', 1e6 * u.km , 'Distance from Sun (km)')

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (AU),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,3.261410056954775e-05 AU,5429,3.7,4.3 km / s,1407.6,4222.6,57900000.0 km,0.3074910076243485 AU,...,0.2410958904109589 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,8.091024252793726e-05 AU,5243,8.9,10.4 km / s,-5832.5,2802.0,108200000.0 km,0.7185931156438579 AU,...,0.6156164383561643 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,8.526859333165629e-05 AU,5514,9.8,11.2 km / s,23.9,24.0,149600000.0 km,0.9833027656856883 AU,...,1.0005479452054795 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,2.3228940249882847e-05 AU,3340,1.6,2.4 km / s,655.7,708.7,384000.0 km,0.0024265051253834456 AU,...,0.0747945205479452 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,4.540171573444728e-05 AU,3934,3.7,5.0 km / s,24.6,24.7,228000000.0 km,1.3817041581728877 AU,...,1.8821917808219177 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,0.0009557890050904314 AU,1326,23.1,59.5 km / s,9.9,9.9,778500000.0 km,4.950605222752011 AU,...,11.865753424657534 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,0.0008057333933697493 AU,687,9.0,35.5 km / s,10.7,10.7,1432000000.0 km,9.074995477191642 AU,...,29.443835616438356 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,0.0003417027245161184 AU,1270,8.7,21.3 km / s,-17.2,17.2,2867000000.0 km,18.26697122902298 AU,...,83.8054794520548 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,0.0003310742309917116 AU,1638,11.0,23.5 km / s,16.1,16.1,4515000000.0 km,29.887457482374447 AU,...,163.83561643835617 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,1.588257900250983e-05 AU,1850,0.7,1.3 km / s,-153.3,153.3,5906400000.0 km,29.658176144080638 AU,...,248.1095890410959 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [816]:
to_AU('Distance from Sun (km)')
df.rename(columns={'Distance from Sun (km)': 'Distance from Sun (AU)'}, inplace=True)

In [817]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (AU)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (AU)', 'Perihelion (AU)',
       'Aphelion (AU)', 'Semi-Major Axis (AU)', 'Orbital Period (years)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [821]:
show_these = [
    'Perihelion (AU)',
    'Aphelion (AU)',
    'Semi-Major Axis (AU)',
    'Diameter (AU)'
]
earth = df.loc[2]

for col in show_these:
    print(f"{col}: {earth[col]}")

Perihelion (AU): 0.9833027656856883 AU
Aphelion (AU): 1.0167257012970305 AU
Semi-Major Axis (AU): 1.0000142334913595 AU
Diameter (AU): 8.526859333165629e-05 AU

In [822]:
df.to_csv("units.csv", index=False)